### ISSUE TITLE
Re-draft HOWTO Obtain Load Balancer IP's

### ISSUE THREAD

**Issue by 7hunderbird** [starkandwayne/codex#34]
In the `aws.md` file there's a section that reads:

```
properties:
  cc:
    security_group_definitions:
    - name: load_balancer:
      rules:
      - destination: YOUR LOAD BALANCER IP1
        protocol: all
      - destination: YOUR LOAD BALANCER IP2
        protocol: all
```

Add a section that helps to explain how to get those IP addresses.
